### PR TITLE
Fixed tiny errors and pizza hut & express in MultiWOZ 2.2

### PR DESCRIPTION
**Pull request by Tomiinek**
This PR fixes two kinds of annotation errors of the **MultiWOZ 2.2** dataset:

- The dataset does not distinguish between the restaurants named `pizza express fen ditton` and `pizza hut fen ditton` and contains them both in the lists valid slot values. See the dialogue ID `MUL0015.json` for an example.
- Some frames are recognized as `{hotel, restaurant}-name` even though they describe `hotel-type`, etc. and the names are propagated in conversations. So they are offered in the lists of valid slot values and the propagation also results in hallucinated values. See the dialogue ID `MUL0152.json` for an example.

### CODE REVIEW

**Comment by XiaoxueZang** [comment]
Hi Tomas, 

Thanks so much for your fix! Could you please revert your last commit f002357 and just merge your fixes to MultiWOZ 2.2? We are trying to maintain a fixed version to reduce the confusions.

Thanks,
Xiaoxue

**Comment by Tomiinek** [comment]
Hello @XiaoxueZang , ok I understand. So should I revert also the changes in test files to make the whole thing backward compatible?

**Comment by XiaoxueZang** [comment]
Hi Tomas, I've checked the change you made on the test set and I think you don't need to revert your change because they have little affect on the benchmarks. Restaurant-name is defined as a non-categorical slot, meaning that its value is based on a span in the utterance. If the slot value is "pizza express fen ditton", it's impossible for the benchmark models we used in the paper to predict "pizza hut fen ditton" in the utterances (at least for the examples in the test files). Though predicting any of the values in the groundtruth state value list is counted as correct when computing the joint goal accuracy, the models have no chance to get one point by predicting the wrong "pizza hut fen ditton" when the real value is "pizza express fen ditton".

**Comment by Tomiinek** [comment]
I see, thank you for discussing. I reverted the last commit, so it should be ready to merge now :slightly_smiling_face:

**Pull request merged**
